site_dir: '../siv3d.github.io'

# Project information
site_name: Siv3D Documentation
site_description: "Siv3D: An open source C++17 library for creative coding" 
site_author: Ryo Suzuki
site_url: https://siv3d.github.io/

# Copyright
copyright: Copyright (c) 2018 - present, Ryo Suzuki<br>Copyright (c) 2018 - present, OpenSiv3D Project

# Theme
theme:
  name: 'material'
  language: 'ja'
  favicon: 'assets/images/favicon.ico'
  logo:
    icon: 'code'
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ja'
    tokenizer: '[\s　、。，．がのをにへとでやかもる「」『』]+'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/Siv3D'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - siv3d_styles.css

# Page tree
nav:
  - Home: index.md
