site_dir: '../siv3d.github.io'

# Project information
site_name: Siv3D
site_description: "Siv3D: An open source C++17 library for creative coding" 
site_author: Ryo Suzuki
site_url: https://siv3d.github.io/

# Copyright
copyright: Copyright (c) 2018 - present, Ryo Suzuki<br>Copyright (c) 2018 - present, OpenSiv3D Project

# Theme
theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo:
    icon: 'code'
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/Siv3D/OpenSiv3D'
    - type: 'twitter'
      link: 'https://twitter.com/Siv3D'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - siv3d_styles.css

# Page tree
nav:
  - English: 
    - Getting started with Siv3D: index.md
    - Tutorial:
      - 1. First steps: tutorial/basic.md
      - 2. Drawing shapes: tutorial/shape.md
    - Reference:
      - Fullscreen: reference/fullscreen.md
      - JSON file: reference/json.md
    - Sample:
      - Game: sample/game.md
      - Application: sample/app.md
    - Community: community/community.md
    - Siv3D Store: store/store.md
  - 日本語:
    - Siv3D をはじめよう: ja-jp/index.md
    - チュートリアル:
      - 1. Siv3D の基本: ja-jp/tutorial/basic.md
      - 2. 図形を描く: ja-jp/tutorial/shape.md
    - リファレンス:
      - フルスクリーン: ja-jp/reference/fullscreen.md
      - JSON ファイル: ja-jp/reference/json.md
    - サンプル:
      - ゲーム: ja-jp/sample/game.md
      - アプリ: ja-jp/sample/app.md
    - コミュニティ: ja-jp/community/community.md
    - Siv3D ストア: ja-jp/store/store.md

