site_dir: '../siv3d.github.io'

# Project information
site_name: Siv3D
site_description: "Siv3D: An open source C++17 library for creative coding" 
site_author: Ryo Suzuki
site_url: https://siv3d.github.io/

# Copyright
copyright: Copyright (c) 2018 - present, Ryo Suzuki<br>Copyright (c) 2018 - present, OpenSiv3D Project

# Theme
theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo:
    icon: 'code'
  palette:
    primary: 'blue'
    accent: 'blue'
  feature:
    tabs: true
extra:
  search:
    language: 'en'
  social:
    - type: 'github'
      link: 'https://github.com/Siv3D/OpenSiv3D'
    - type: 'twitter'
      link: 'https://twitter.com/Siv3D'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - siv3d_styles.css

# Page tree
nav:
  - English: 
    - Getting started with Siv3D: index.md
    - Tutorial:
      - 1. First steps: tutorial/basic.md
      - 2. Drawing shapes: tutorial/shape.md
      - 3. Animation: tutorial/animation.md
      - 4. 2D intersection: tutorial/2d-intersection.md
      - 5. Drawing images: tutorial/texture.md
      - 6. Data structures: tutorial/data-structures.md
      - 7. Formatting and parsing: tutorial/formatting.md
      - 8. Using fonts: tutorial/font.md
      - 9. GUI: tutorial/gui.md
      - 10. Scene and window: tutorial/window.md
      - 11. Keyboard: tutorial/keyboard.md
      - 12. Mouse: tutorial/mouse.md
      - 13. Audio: tutorial/audio.md
      - 14. Random: tutorial/random.md
      - 15. 2D render states: tutorial/2d-renderstates.md  
    - Reference:
      - Fullscreen: reference/fullscreen.md
      - JSON file: reference/json.md
      - 2D shadow: reference/2d-shadow.md
      - 2D geometry: reference/2d-geometry.md
      - NavMesh: reference/navmesh.md
      - Natural language processing: reference/nlp.md
      - Math parser: reference/math-parser.md
    - Sample:
      - Game: sample/game.md
      - Application: sample/app.md
      - Visual effect: sample/visual.md
      - Geme template: sample/game-template.md
    - Community: community/community.md
    - Siv3D Store: store/store.md
  - 日本語:
    - Siv3D をはじめよう: ja-jp/index.md
    - チュートリアル:
      - 1. Siv3D の基本: ja-jp/tutorial/basic.md
      - 2. 図形を描く: ja-jp/tutorial/shape.md
      - 3. 動きを作る: ja-jp/tutorial/animation.md
      - 4. あたり判定: ja-jp/tutorial/2d-intersection.md
      - 5. 画像を描く: ja-jp/tutorial/texture.md
      - 6. データ構造: ja-jp/tutorial/data-structures.md
      - 7. 文字列と数値の変換: ja-jp/tutorial/formatting.md
      - 8. フォントを使う: ja-jp/tutorial/font.md
      - 9. GUI: ja-jp/tutorial/gui.md
      - 10. シーンとウィンドウ: ja-jp/tutorial/window.md
      - 11. キーボード入力: ja-jp/tutorial/keyboard.md
      - 12. マウス入力: ja-jp/tutorial/mouse.md
      - 13. オーディオ再生: ja-jp/tutorial/audio.md
      - 14. ランダム: ja-jp/tutorial/random.md
      - 15. 2D レンダーステート: ja-jp/tutorial/2d-renderstates.md           
    - リファレンス:
      - フルスクリーン: ja-jp/reference/fullscreen.md
      - JSON ファイル: ja-jp/reference/json.md
      - 2D 図形の影: ja-jp/reference/2d-shadow.md
      - 2D 計算幾何: ja-jp/reference/2d-geometry.md
      - ナビメッシュ: ja-jp/reference/navmesh.md
      - 自然言語処理: ja-jp/reference/nlp.md
      - 数式処理: ja-jp/reference/math-parser.md
    - サンプル:
      - ゲーム: ja-jp/sample/game.md
      - アプリ: ja-jp/sample/app.md
      - ビジュアル表現: ja-jp/sample/visual.md
      - ゲーム開発のテンプレート: ja-jp/sample/game-template.md
    - コミュニティ: ja-jp/community/community.md
    - Siv3D ストア: ja-jp/store/store.md

